name: Build and Deploy Pong

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.64

      - name: Build with Makefile
        run: |
          make web

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './web'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4